package lunartools.audiocutter;

public enum SimpleEvents {
	EXIT,
	MODEL_FRAMESIZECHANGED,
	MODEL_MEDIAFILECHANGED,
	MODEL_AUDIODATACHANGED,
	MODEL_AUDIOSECTIONSCHANGED,
	MODEL_ZOOMCHANGED,
	MODEL_ZOOMRANGECHANGED,
	MODEL_SELECTIONCHANGED,
	MODEL_CURSORCHANGED,
	MODEL_MOUSESAMPLENUMBERCHANGED,
	MODEL_PLAYCURSORCHANGED,
	MODEL_AUDIOPLAYERBUFFERSIZECHANGED,
	MODEL_SELECTEDSECTIONSCHANGED,
	MODEL_FFMPEGEXECUTABLESELECTED,
	MODEL_PROJECTDIRTCHANGED,
	MODEL_RECENTMEDIAFILESLISTCHANGED,
	MODEL_RECENTPROJECTSFILELISTCHANGED
	;
}
