package lunartools.audiocutter.common.model;

public enum SimpleEvents {
	EXIT,
	MODEL_FRAMESIZECHANGED,
	MODEL_MEDIAFILECHANGED,
	MODEL_AUDIODATACHANGED,
	MODEL_AUDIOSECTIONSCHANGED,
	MODEL_ZOOMFACTORCHANGED,
	MODEL_ZOOMRANGECHANGED,
	MODEL_AMPLITUDEZOOMCHANGED,
	MODEL_SELECTIONCHANGED,
	MODEL_CURSORCHANGED,
	MODEL_MOUSESAMPLENUMBERCHANGED,
	MODEL_PLAYCURSORCHANGED,
	MODEL_SELECTEDSECTIONSCHANGED,
	MODEL_FFMPEGEXECUTABLESELECTED,
	MODEL_PROJECTDIRTCHANGED,
	MODEL_RECENTMEDIAFILESLISTCHANGED,
	MODEL_RECENTPROJECTSFILELISTCHANGED
	;
}
